[package]
name = "tin-metal"
version = "0.1.0"
edition = "2021"

[lib]
name = "metal"

[dependencies]
objc2 = { workspace = true }
objc2-foundation = { workspace = true }
objc2-metal = { workspace = true }
objc2-quartz-core = { workspace = true }
block2 = { workspace = true }
objc2-app-kit = { workspace = true }
objc2-core-foundation = "0.3"
hashbrown = "0.15"
spirv-cross2 = { version = "0.7", default-features = false, features = ["msl"] }
