use objc2_metal::{MTLPixelFormat, MTLVertexFormat};

pub struct Format {
    pub raw: MTLPixelFormat,
    pub pixel: u32,
}

const fn f(raw: MTLPixelFormat, pixel: u32) -> Format {
    Format { raw, pixel }
}

pub fn format(ordinal: u32) -> Format {
    match ordinal {
        0 => f(MTLPixelFormat::R8Unorm, 1),
        1 => f(MTLPixelFormat::R8Snorm, 1),
        2 => f(MTLPixelFormat::RG8Unorm, 2),
        3 => f(MTLPixelFormat::RG8Snorm, 2),
        6 => f(MTLPixelFormat::RGBA8Unorm, 4),
        7 => f(MTLPixelFormat::RGBA8Snorm, 4),
        8 => f(MTLPixelFormat::R16Unorm, 2),
        9 => f(MTLPixelFormat::R16Snorm, 2),
        10 => f(MTLPixelFormat::RG16Unorm, 4),
        11 => f(MTLPixelFormat::RG16Snorm, 4),
        14 => f(MTLPixelFormat::RGBA16Unorm, 8),
        15 => f(MTLPixelFormat::RGBA16Snorm, 8),
        16 => f(MTLPixelFormat::R8Uint, 1),
        17 => f(MTLPixelFormat::R8Sint, 1),
        18 => f(MTLPixelFormat::RG8Uint, 2),
        19 => f(MTLPixelFormat::RG8Sint, 2),
        22 => f(MTLPixelFormat::RGBA8Uint, 4),
        23 => f(MTLPixelFormat::RGBA8Sint, 4),
        24 => f(MTLPixelFormat::R16Uint, 2),
        25 => f(MTLPixelFormat::R16Sint, 2),
        26 => f(MTLPixelFormat::RG16Uint, 4),
        27 => f(MTLPixelFormat::RG16Sint, 4),
        30 => f(MTLPixelFormat::RGBA16Uint, 8),
        31 => f(MTLPixelFormat::RGBA16Sint, 8),
        32 => f(MTLPixelFormat::R32Uint, 4),
        33 => f(MTLPixelFormat::R32Sint, 4),
        34 => f(MTLPixelFormat::RG32Uint, 8),
        35 => f(MTLPixelFormat::RG32Sint, 8),
        38 => f(MTLPixelFormat::RGBA32Uint, 16),
        39 => f(MTLPixelFormat::RGBA32Sint, 16),
        40 => f(MTLPixelFormat::R16Float, 2),
        41 => f(MTLPixelFormat::RG16Float, 4),
        43 => f(MTLPixelFormat::RGBA16Float, 8),
        44 => f(MTLPixelFormat::R32Float, 4),
        45 => f(MTLPixelFormat::RG32Float, 8),
        47 => f(MTLPixelFormat::RGBA32Float, 16),
        48 => f(MTLPixelFormat::RGB10A2Unorm, 4),
        49 => f(MTLPixelFormat::RGB10A2Uint, 4),
        50 => f(MTLPixelFormat::RG11B10Float, 4),
        51 => f(MTLPixelFormat::Depth32Float, 4),
        52 => f(MTLPixelFormat::Depth32Float_Stencil8, 8),
        53 => f(MTLPixelFormat::Depth24Unorm_Stencil8, 4),
        54 => f(MTLPixelFormat::Depth16Unorm, 2),
        55 => f(MTLPixelFormat::Stencil8, 1),
        _ => unreachable!("format {ordinal} has no metal form"),
    }
}

pub fn vertex(ordinal: u32) -> MTLVertexFormat {
    match ordinal {
        0 => MTLVertexFormat::UCharNormalized,
        1 => MTLVertexFormat::CharNormalized,
        2 => MTLVertexFormat::UChar2Normalized,
        3 => MTLVertexFormat::Char2Normalized,
        4 => MTLVertexFormat::UChar3Normalized,
        5 => MTLVertexFormat::Char3Normalized,
        6 => MTLVertexFormat::UChar4Normalized,
        7 => MTLVertexFormat::Char4Normalized,
        8 => MTLVertexFormat::UShortNormalized,
        9 => MTLVertexFormat::ShortNormalized,
        10 => MTLVertexFormat::UShort2Normalized,
        11 => MTLVertexFormat::Short2Normalized,
        12 => MTLVertexFormat::UShort3Normalized,
        13 => MTLVertexFormat::Short3Normalized,
        14 => MTLVertexFormat::UShort4Normalized,
        15 => MTLVertexFormat::Short4Normalized,
        16 => MTLVertexFormat::UChar,
        17 => MTLVertexFormat::Char,
        18 => MTLVertexFormat::UChar2,
        19 => MTLVertexFormat::Char2,
        20 => MTLVertexFormat::UChar3,
        21 => MTLVertexFormat::Char3,
        22 => MTLVertexFormat::UChar4,
        23 => MTLVertexFormat::Char4,
        24 => MTLVertexFormat::UShort,
        25 => MTLVertexFormat::Short,
        26 => MTLVertexFormat::UShort2,
        27 => MTLVertexFormat::Short2,
        28 => MTLVertexFormat::UShort3,
        29 => MTLVertexFormat::Short3,
        30 => MTLVertexFormat::UShort4,
        31 => MTLVertexFormat::Short4,
        32 => MTLVertexFormat::UInt,
        33 => MTLVertexFormat::Int,
        34 => MTLVertexFormat::UInt2,
        35 => MTLVertexFormat::Int2,
        36 => MTLVertexFormat::UInt3,
        37 => MTLVertexFormat::Int3,
        38 => MTLVertexFormat::UInt4,
        39 => MTLVertexFormat::Int4,
        40 => MTLVertexFormat::Half,
        41 => MTLVertexFormat::Half2,
        42 => MTLVertexFormat::Half3,
        43 => MTLVertexFormat::Half4,
        44 => MTLVertexFormat::Float,
        45 => MTLVertexFormat::Float2,
        46 => MTLVertexFormat::Float3,
        47 => MTLVertexFormat::Float4,
        48 => MTLVertexFormat::UInt1010102Normalized,
        50 => MTLVertexFormat::FloatRG11B10,
        _ => unreachable!("format {ordinal} has no metal vertex form"),
    }
}
